### ISSUE TITLE
Request: Documentation

### ISSUE THREAD

**Issue by JeffRockatansky** [VitJRBOG/CleaningVk#1]
Having docs (at least launch instructions at least in Readme.md) would be nice. Might help with it later.

**Comment by VitJRBOG** [comment]
Done! But since my English is bad, I wrote in Russian.

**Comment by JeffRockatansky** [comment]
@VitJRBOG норм, могу перевести

**Comment by VitJRBOG** [comment]
@JeffRockatansky токены я скрыл. То, что на скринах сайта ВК отображено - просто набор символов, чтобы нагляднее было.
